### ISSUE TITLE
Request timeout doesn't seem to work

### ISSUE THREAD

**Issue by robert7** [d1vanov/QEverCloud#22]
Hi,
I think there is a problem in http.c simpleDownload() (or ReplyFetcher/ReplyFetcherLauncher) where it waits indefinitely after network error. 
To reproduce (e.g. using quentier): 
1. start sync with working network .. all is expected to work
2. disconnect network
3. repeat sync - it get stuck

Unfortunately I'm quite bad with Qt... but I could debug until the point that the line "loop.exec(QEventLoop::ExcludeUserInputEvents);" in simpleDownload() gets executed, but the event loop never gets terminated. So the line "fetcherLauncher->deleteLater();" never gets reached. Also "setError()" in ReplyFetcher never gets called.. then signal "replyFetched" is not emitted therefore loop doesn't get terminated.

The timeout works if the connection isn't available from the application start. But doesn't if the connection is available, but then drops (or if its unstable - e.g. bad wifi).

The expected behavior is, that on network error (e.g. after timeout) error is set and then exception thrown.

**Comment by d1vanov** [comment]
You are right in that network timeout doesn't work in current QEverCloud from master branch. I noticed that too and fixed it in development branch, here's [the commit](https://github.com/d1vanov/QEverCloud/commit/4d00683c7f83ba78002d96b9d9526cbf34ce8736). I haven't ported this fix to master yet because for me it caused unexpected issues in some situations. For example, if I have some hundreds of in flight network requests, the thread processing them gets overwhelmed with callbacks and some requests just don't have the CPU capacity to possibly finish in time. In the latest development I made it possible to specify the exact period for network timeout but by default it is not set to anything i.e. timeout does not work. At least this way it would not break the existing behaviour and any apps which might depend on it.

**Comment by robert7** [comment]
thanks for reply!
I will compare the code and retry with the changes from development branch

**Comment by robert7** [comment]
I updated QEverCloud in my project to v4.1 and the timeouts now seem to work fine.
Thanks!

**Comment by robert7** [comment]
One more question: does the timeout (in the development branch) currently apply to "connection time" or also to the time until the request is fully read ("request total time") or to both?

**Comment by d1vanov** [comment]
Perhaps "connection timeout" isn't really a good term because here's how it actually works:
1. Request processing is [started](https://github.com/d1vanov/QEverCloud/blob/master//QEverCloud/src/http.cpp#L38), last network time is set to the current timestamp and timer is set up to find whether no progress has been made on this request
2. As the download goes, [callback](https://github.com/d1vanov/QEverCloud/blob/master//QEverCloud/src/http.cpp#L62) is fired periodically which updates the last network time
3. In the [callback for timer](https://github.com/d1vanov/QEverCloud/blob/master//QEverCloud/src/http.cpp#L67) there's a check for no progress over the period of time larger than what's currently called "connection timeout". If so, the request is considered timed out i.e. failed.

**Comment by robert7** [comment]
OK. Thanks for explanation.
