### ISSUE TITLE
Capitalisation in SONAME

### ISSUE THREAD

**Issue by spwhitton** [d1vanov/QEverCloud#9]
Hello,

I noticed that the SONAMEs for this library are `libqt5qevercloud.so.3` and `libqt4qevercloud.so.3`, while all other Qt libs capitalise the 'q', e.g. `libQt5PrintSupport.so.5`.

Is this deliberate?

Thanks.

**Comment by d1vanov** [comment]
Hello,

Yes, such naming is intentional. I used [qtkeychain](https://packages.debian.org/ru/source/sid/qtkeychain) library naming as an inspiration, only making it even more explicit by mentioning both 4 and 5 versions of Qt framework in the library names of QEverCloud. I don't think it is a good idea to use capitalized names because it would make the library name look like it's one of the official Qt libraries, like the one you mentioned.

**Comment by spwhitton** [comment]
Thank you for your reply!

-- 
Sean Whitton

**Comment by d1vanov** [comment]
You are welcome! :smiley:
